{% set name = "mplstereonet" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mplstereonet-{{ version }}.tar.gz
  sha256: 2ce630b14973a0b2f7d65cabb8d03fada2a8fda8b9b922d4cf335ecfcb442372

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - matplotlib-base >=1.1
    - numpy >=1.1
    - python >={{ python_min }}
    - shapely

test:
  imports:
    - mplstereonet
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/joferkington/mplstereonet/
  summary: Stereonets for matplotlib
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AndrewAnnex
